apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendship-service
  labels:
    app: friendship-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friendship-service
  template:
    metadata:
      labels:
        app: friendship-service
    spec:
      containers:
      - name: friendship-service
        image: friendship-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: FRIENDSHIP_DB_PATH
          value: /data/friendships.db
        - name: FRIENDSHIP_API_PORT
          value: "5000"
        - name: FRIENDSHIP_LOG_LEVEL
          value: INFO
        volumeMounts:
        - name: friendship-data
          mountPath: /data
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /friends
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: friendship-data
        persistentVolumeClaim:
          claimName: friendship-data-pvc
