apiVersion: v1
kind: Namespace
metadata:
  name: friendship
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: friendship-data-pvc
  namespace: friendship
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendship-service
  namespace: friendship
  labels:
    app: friendship-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friendship-service
  template:
    metadata:
      labels:
        app: friendship-service
    spec:
      containers:
      - name: friendship-service
        image: kbrar8/friendship-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FRIENDSHIP_DB_PATH
          value: /data/friendships.db
        - name: FRIENDSHIP_API_PORT
          value: "5000"
        - name: FRIENDSHIP_LOG_LEVEL
          value: INFO
        volumeMounts:
        - name: friendship-data
          mountPath: /data
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /friends
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /friends
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: friendship-data
        persistentVolumeClaim:
          claimName: friendship-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: friendship-service
  namespace: friendship
  labels:
    app: friendship-service
spec:
  selector:
    app: friendship-service
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
