apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: friendship-data-pvc
  namespace: friendship
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendship-service
  namespace: friendship
  labels:
    app: friendship-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friendship-service
  template:
    metadata:
      labels:
        app: friendship-service
    spec:
      containers:
      - name: friendship-service
        image: kbrar8/friendship-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FRIENDSHIP_DB_PATH
          value: /data/friendships.db
        - name: FRIENDSHIP_API_PORT
          value: "5000"
        - name: FRIENDSHIP_LOG_LEVEL
          value: INFO
        - name: FRIENDSHIP_API_KEY
          valueFrom:
            secretKeyRef:
              name: friendship-api-secret
              key: api-key
        volumeMounts:
        - name: friendship-data
          mountPath: /data
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: friendship-data
        persistentVolumeClaim:
          claimName: friendship-data-pvc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: friendship-service-hpa
  namespace: friendship
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: friendship-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: friendship-service
  namespace: friendship
  labels:
    app: friendship-service
spec:
  selector:
    app: friendship-service
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: friendship-route
  namespace: friendship
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`friendship.kanwarpal.com`)
      kind: Rule
      services:
        - name: friendship-service
          port: 80
  tls:
    certResolver: default
